### ISSUE TITLE
Add trakt ID cache from aniTrakt

### ISSUE THREAD

**Issue by infanf** [infanf/myanili#55]
https://anitrakt.huere.net/db/db_index_movies.php
https://anitrakt.huere.net/db/db_index_shows.php

**Comment by infanf** [comment]
@nattadasu fyi

**Comment by infanf** [comment]
Alternative solution: build cache from simkl api

**Comment by infanf** [comment]
alternative solution not possible: simkl doesn't return external ids that were not part of the initial request.

**Comment by nattadasu** [comment]
> alternative solution not possible: simkl doesn't return external ids that were not part of the initial request.

Using PowerShell and adding `extended=full` param in request returns external ids. But yeah, it's not really good (as it might take some times to load).

Example:

```ps1
((Invoke-WebRequest -Uri "https://api.simkl.com/anime/40398?extended=full&client_id=$($Env:SIMKL_CLIENT_ID)" -ContentType "application/json").Content | ConvertFrom-Json).ids
```

```yaml
simkl       : 40398
slug        : hunter-x-hunter
anidb       : 8550
tw          : hunter_anime
tmdb        : 46298
imdb        : tt2098220
ann         : 13262
mal         : 11061
anfo        : 4947
offjp       : http://www.ntv.co.jp/hunterhunter/
wikien      : Hunter_x_hunter
wikijp      : HUNTER×HUNTER_(2011年のアニメ)
allcin      : 340525
crunchyroll : hunter-x-hunter
tvdbslug    : hunter-x-hunter-2011
```
